spring:
  redis:
    database: 0
    host: 47.105.165.224
    port: 6379
    password: lazyrabbit
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-wait: 10000
        max-idle: 20

